architecture: RN50
batch_size: 256
behavioral_rsa: false
criterion: CrossEntropyLoss
cuda: -1
dataset_type: imagenet
debug_logging: true
debug_resume: false
early_stopping_patience: 2
hf_cache_dir: /tmp/hf_cache
hf_dataset_name: ILSVRC/imagenet-1k
hf_shuffle_buffer_size: 10000
logger: None
lr: 0.1
lr_scheduler: cosineannealinglrwithwarmup
lr_warmup_duration: 1
max_duration: 2
momentum: 0.9
no_wandb: true
num_classes: 1000
num_train_samples: 1281167
num_val_samples: 50000
num_workers: 8
opt: sgd
perturb_epoch: 0
perturb_length: 0
perturb_seed: null
perturb_type: none
prefetch_factor: 4
pretrained: false
random_seed: 1
save_path: training_runs/resnet50_imagenet_debug/baseline_seed1
stream_from_hf: true
training_mode: scratch
wandb_entity: null
wandb_project: null
weight_decay: 0.0001
